config/routes.rb
Rails.application.routes.draw do
  devise_for :recruiters, controllers: {registrations: "recruiters/registrations"}
  resources :cities
  resources :expertises
  devise_for :users, controllers: {registrations: "users/registrations", omniauth_callbacks: "callbacks"}
  get 'recruiter/home'
  get 'recruiter/favoriteDevelopers'
  get 'recruiter/suggestedDevelopers'
  get 'developer/home'
  get 'home/index'
  get 'skills/:skill', to: 'profiles#index', as: "skill"
  post '/pay' => 'charge#pay'
  resources :profiles
  resources :favorite_profiles, only: [:create, :destroy]

  root 'home#index'

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  require 'csv'
  cattr_accessor :crepos

  belongs_to :user
  has_many :skillsets
  has_many :skills, through: :skillsets
  has_many :educations
  has_many :portfolios
  has_many :works
  has_and_belongs_to_many :expertises
  has_and_belongs_to_many :cities
  has_many :devpurchaseds
  has_many :recruiters, through: :devpurchaseds

  accepts_nested_attributes_for :works, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :educations, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :portfolios, :allow_destroy => true

  has_attached_file :image, styles: { medium: "300x500>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  def words
    scan(/\w[\w\'\-]*/)
  end

  def all_skills=(names)
    self.skills = names.split("-").map do |name|
      Skill.where(name: name.strip).first_or_create!
    end
  end

  def all_skills
    self.skills.map(&:name).join("-")
  end

  def self.tagged_with(name)
    Skill.find_by_name!(name).profiles
  end

  #def shortbio
  #  bio.length > 100? bio[0..100] + "..." : bio
  #end

  is_impressionable

  self.per_page = 8

  def score
   score = 0

   if self.bio.present?
     if self.bio.length < 100
       score += 2
     elsif self.bio.length > 200 && self.bio.length < 299
       score += 4
     elsif self.bio.length > 300
       score += 5
     end
   else
     score = 0
   end

   if self.image.present?
     score += 5
   end
   if self.location.present?
     score += 2
   end
   if self.phone.present?
     score += 2
   end

   if self.TwitterLink.present?
     score += 1
   end
   if self.GithubLink.present?
     score += 2
   end
   if self.StackLink.present?
     score += 2
   end
   if self.DribbbleLink.present?
     score += 3
   end
   if self.MediumLink.present?
     score += 3
   end

   if self.willingToRelocate == true
     score += 5
   end
   if self.workAbroad == true
     score += 5
   end

   if self.portfolios.present?
     score += 5 * self.portfolios.count
   end

   if self.works.present?
     score += 5 * self.works.count
     self.works.each do |work|
       if (work.finishDate.year - work.startDate.year).to_i <= 1
         score += 2
       elsif (work.finishDate.year - work.startDate.year).to_i >= 2 && (work.finishDate.year - work.startDate.year).to_i <= 3
         score += 3
       elsif (work.finishDate.year - work.startDate.year).to_i >= 4 && (work.finishDate.year - work.startDate.year).to_i <= 5
         score += 4
       elsif (work.finishDate.year - work.startDate.year).to_i >= 5 && (work.finishDate.year - work.startDate.year).to_i <= 6
         score += 5
       elsif (work.finishDate.year - work.startDate.year).to_i > 7
         score += 10
       end

       workrole = work.position.downcase
       if workrole.include? "internship"
         score += 5
       elsif workrole.include? "senior"
         score += 10
       elsif workrole.include? "graduate"
         score += 15
       elsif workrole.include? "architect"
         score += 20
       elsif workrole.include? "engineer"
         score += 20
       elsif workrole.include? "manager"
         score += 20
       elsif workrole.include? "scientist"
         score += 20
       end

       splitDescription = work.workDescription.downcase.split(' ')
       keywords = ['teamwork', 'developed', 'enhanced', 'transformed', 'achieved','grew', 'introduced', 'project', 'awarded']
       splitDescription.select {|word| keywords.include?(word)}.each do |word|
         score += 2
       end

       workname = work.companyName
       topcompanies = CSV.read('lib/assets/topcampanies.csv',{encoding: "UTF-8", headers:true, header_converters: :symbol, converters: :all})
       hashed_topcompanies = topcompanies.map {|d| d.to_hash}
       hashed_topcompanies.select {|topcompanies| topcompanies[:companyname].include?(workname)}.each do |s|
         if s[:companyrank] <= 5
           score += 100
         elsif s[:companyrank] >= 6 && s[:companyrank] <=10
           score += 75
         elsif s[:companyrank] >= 11 && s[:companyrank] <=50
           score += 50
         elsif s[:companyrank] >=51 && s[:companyrank] <= 100
           score += 25
         elsif s[:companyrank] >=101 && s[:companyrank] <= 200
           score += 10
         elsif s[:companyrank] >= 201 && s[:companyrank] <=300
           score += 5
         end
       end

     end
   end

   if self.educations.present?
     score += 5 * self.educations.count
     self.educations.each do |e|
       universityname = e.university
       topuniversities = CSV.read('lib/assets/topuniversities.csv',{encoding: "UTF-8", headers:true, header_converters: :symbol, converters: :all})
       hashed_topuniversities = topuniversities.map {|d| d.to_hash}
       hashed_topuniversities.select {|topuniversities| topuniversities[:universityname].include?(universityname)}.each do |s|
         if s[:universityrank] <= 10
           score += 100
         elsif s[:universityrank] >= 11 && s[:universityrank] <=25
           score += 75
         elsif s[:universityrank] >= 26 && s[:universityrank] <=50
           score += 50
         elsif s[:universityrank] >=51 && s[:universityrank] <= 100
           score += 25
         elsif s[:universityrank] >=101 && s[:universityrank] <= 150
           score += 10
         end
       end
       case e.level
         when "1st"
          score += 15
         when "2.1"
          score += 10
         when "2.2"
          score += 5
         when "3rd"
          score += 1
        end
        case e.degreetype
          when "Bachelor Degree"
            score += 5
          when "Masters Degree"
            score += 10
          when "PhD"
            score += 20
        end
     end
   end

   if self.user.github_profile.present?
     score += 50
     if user.github_profile.followers > 3
       score += 1000
     end
     #no need to use count because public_repo is a number
     score += 5 * user.github_profile.public_repo

     Profile.crepos.each do |repo|
       if repo.watchers > 100
         score += 1000
       end
       if repo.forks > 100
         score += 1000
       end
       case repo.language.to_s.downcase
       when "ruby"
         score += 2
       when "objective-c"
         score += 2
       when "java"
         score += 2
       when "c++"
         score += 2
       when "python"
         score += 2
       when "javascript"
         score += 2
       when "php"
         score += 2
       end
       if repo.stargazers_count > 1
         score += 10
       end
     end
   end

   case self.experiance
     when "1-2 years"
       score += 5
     when "2-3 years"
       score += 10
     when "3-4 years"
       score += 15
     when "5-6 years"
       score += 20
     when "6-7 years"
       score += 25
     when "7+ years"
       score += 30
   end

   if self.skills.present?
    score += 2 * skills.count
    self.skills.each do |skill|
      case skill.name.downcase
      when "ruby"
        score += 2
      when "objective-c"
        score += 2
      when "java"
        score += 2
      when "c++"
        score += 2
      when "python"
        score += 2
      when "javascript"
        score += 2
      when "php"
        score += 2
      end
    end
   end

   score
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]
  before_action :authenticate_person!, only: [:index, :show]
  impressionist actions: [:show], unique: [:session_hash]

  def index
    @search = Profile.search(params[:q])
    @profiles = @search.result(distinct: true).paginate(page: params[:page], per_page: params[:per_page])
    u = Profile.all
    @universities = u.map { |profile| profile.educations.map {|e| e.university}}.flatten

    #if params[:skill]
    #  @profiles = Profile.tagged_with(params[:id])
  #  else
    #  @profiles = Profile.all
  #  end

  end

  def show
    impressionist(@profile)
    unless @profile.user.github_profile.nil?
      client = Octokit::Client.new(:access_token => @profile.user.github_profile.access_token)
      Profile.crepos = @repositories = client.repos
    end
    @joined = false
    if !current_recruiter.nil? && !current_recruiter.profiles.nil?
      @joined = current_recruiter.profiles.include?(@profile)
    end
  end

  def new
    @profile = current_user.build_profile
  end

  def edit
  end

  def create
    @profile = current_user.build_profile(profile_params)
    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_profile
      @profile = Profile.find(params[:id])
    end

    def profile_params
      params.require(:profile).permit(:bio, :user_id, :name, :image, :location, :whatAmI, :phone, :experiance,
        :willingToRelocate, :score, :workAbroad, :salary, :UKauthorization, :TwitterLink, :GithubLink, :StackLink, :DribbbleLink, :MediumLink,
        :all_skills, educations_attributes: [:id, :university, :course, :finishdate, :degreetype, :level, :_destroy],
        portfolios_attributes: [:id, :description, :picture, :_destroy],
        works_attributes: [:id, :companyName, :position, :startDate, :finishDate, :workDescription, :_destroy],
        expertise_ids:[], city_ids:[] )
        #need to add images _destroy
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
  def tag_links(skills)
    skills.split(",").map { |skill| link_to skill.strip, skill_path(skill.strip)}.join(", ")
  end
end

app/views/profiles/_education_fields.html.erb
<div class="nested-fields">
  <%= f.label :university %><br>
  <%= f.text_field :university %><br>

  <div class="field">
    <label for="willingToRelocate">Are you willing to relocate?</label>
    <%= f.select :degreetype, ['Bachelor Degree', 'Masters Degree', 'PhD'], {}, :class => 'form-control' %>
  </div>

  <%= f.label :course %><br>
  <%= f.text_field :course %><br>

  <%= f.label :level %><br>
  <%= f.select :level, ['1st','2.1','2.2','3rd'] %><br>

  <%= f.label :finishdate %><br>
  <%= f.date_select :finishdate, :order => [:day, :month, :year] %><br>

  <%= link_to_remove_association "remove education", f %>
</div>

app/views/profiles/_portfolio_fields.html.erb
<div class="nested-fields">
  <%= f.text_area :description %>
  <%= f.file_field :picture %>
  <%= link_to_remove_association "remove", f %>
</div>

app/views/profiles/_work_fields.html.erb
<div class="nested-fields">
  <%= f.label :companyName %><br>
  <%= f.text_field :companyName %><br>

  <%= f.label :position %><br>
  <%= f.text_field :position, :placeholder => "Senior Developer or Internship" %><br>

  <%= f.label :startDate %><br>
  <%= f.date_select :startDate, :order => [:day, :month, :year] %><br>

  <%= f.label :finishDate %><br>
  <%= f.date_select :finishDate, :order => [:day, :month, :year] %><br>

  <%= f.label :workDescription %><br>
  <%= f.text_area :workDescription %><br>

  <%= link_to_remove_association "remove work experiance", f %>
</div>

app/views/profiles/edit.html.erb
<%= render 'form' %>

app/views/profiles/index.html.erb
<div class="indexcontainer">

    <div class="searchform">
      <h1>Find your next developer</h1>
      <hr>
      <div class="formscontainer">
        <%= search_form_for @search do |f|%>
          <div class="form-group">
            <label class="formlabel" for="skill">Search skill:</label>
            <%= f.text_field :bio_or_whatAmI_cont, class: "form-control custom", id: "skill", placeholder: "e.g. Ruby Developer" %>
          </div>
          <div class="form-group">
            <label class="formlabel" for="skill">Minimum years of experience:</label>
            <%= f.text_field :experiance_gt, class: "form-control custom", placeholder: "e.g. 2 Years" %>
          </div>
          <div class="field">
            <label class="formlabel" for="skill">Choose a university:</label><br>
            <%= f.select :educations_university_eq, @universities, :include_blank => "Any University",
             :prompt => "Select university", class: "form-control" %>
          </div>
      </div>
      <hr>
      <div class="aofexpertise">
        <%= f.label "Area of Expertise", class: "formlabel" %><br>
          <%= f.collection_check_boxes :expertises_id_in_any, Expertise.all, :id, :name do |b| %>
          <div class="collection_check_boxes">
            <li>
              <%= b.check_box %>
              <%= b.label %>
            </li>
          </div>
        <% end %>
      </div>
      <div class="aofcity">
      <hr>
        <%= f.label "City searching for developer", class: "formlabel" %><br><br>
        <%= f.collection_check_boxes :cities_id_in_any, City.all, :id, :name do |b| %>
          <div class="collection_check_boxes">
            <li>
              <%= b.check_box %>
              <%= b.label %>
            </li>
          </div>
        <% end %>
      </div>
      <div class="submitbutton">
        <hr>
        <div class="buttonpos">
          <%= f.submit "Search", class: "btn btn-primary btn-lg btn-border custom" %>
        </div>
      </div>
      <% end %>
    </div>


  <div class="profilescontainer" data-no-turbolink="true">
    <% @profiles.each do |profile| %>
      <div class="eachprofile">
        <aside class="profile-card">
          <header>
            <%= link_to profile do %>
              <%= image_tag profile.image.url(:medium) %>
            <% end %>
            <h1><%= profile.name %></h1>
            <h2><%= profile.whatAmI %></h2>
          </header>
          <div class="profile-bio">

          </div>
        </aside>
      </div>
    <% end %>
    <%= will_paginate @profiles %>
  </div>

</div>

app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form' %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<div class="profileHeader">
  <h4 class="textfont views"><%= @profile.impressionist_count %> <i class="fa fa-eye"></i></h4>
  <div class="imageContainer">
    <%= image_tag @profile.image.url(:medium), id: "headshot", class: "imagepos" %>
  </div>
  <div class="infoContainer">
    <br>
    <h4 class="textfont"><%= "Score: #{@profile.score}" %></h4>
    <h1 class="textfont"><%= @profile.name %></h1><hr>
    <h2 class="textfont"><%= @profile.whatAmI %></h2>
    <h4 class="textfont"><%= @profile.all_skills %></h4><hr>
  </div>
  <div class="sociallinks">
    <h2 style= "text-align: center;">
      <%= link_to ("http://#{@profile.TwitterLink}"),{style: "color: #AEA8D3"} do %>
        <i class="fa fa-twitter fa-2x"></i>&nbsp;&nbsp;&nbsp;
      <% end %>
      <%= link_to ("http://#{@profile.GithubLink}"),{style: "color: #AEA8D3"} do %>
        <i class="fa fa-github fa-2x"></i>&nbsp;&nbsp;&nbsp;
      <% end %>
      <%= link_to ("http://#{@profile.StackLink}"),{style: "color: #AEA8D3"} do %>
        <i class="fa fa-stack-overflow fa-2x"></i>&nbsp;&nbsp;&nbsp;
      <% end %>
      <%= link_to ("http://#{@profile.DribbbleLink}"),{style: "color: #AEA8D3"} do %>
        <i class="fa fa-dribbble fa-2x"></i>&nbsp;&nbsp;&nbsp;
      <% end %>
      <%= link_to ("http://#{@profile.MediumLink}"),{style: "color: #AEA8D3"} do %>
        <i class="fa fa-medium fa-2x"></i>
      <% end %>
    </h2>
  </div>
</div>

<div class="summary">
  <h1>Summary</h1>
  <hr>
  <div class="summarybox">
    <p class=""><i><%= @profile.bio %></i></p>
  </div>
</div>

<div class="secondContainer">
  <div class="educationsContainer">
    <h1>Education</h1>
    <div class="eacheducation">
      <% @profile.educations.each do |education| %>
          <h3><i class="fa fa-graduation-cap"></i>&nbsp;&nbsp;<b><%= education.university %> - <%= education.finishdate.year %></b></h3>
          <h4>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= education.level %> in <%= education.course %> <%= education.degreetype %></h4>
          <hr>
      <% end %>
    </div>
  </div>
  <div class="preferenceContainer">
    <h1>Job Preferences</h1>
    <div class="eachPreferences">
      <% if @profile.willingToRelocate == true %>
        <h4><i class="fa fa-map-marker"></i>&nbsp;&nbsp;<%= @profile.name %> is willing to relocate</h4>
      <% else %>
        <h4><i class="fa fa-map-marker"></i>&nbsp;&nbsp;<%= @profile.name %> is not willing to relocate</h4>
      <% end %><hr>
      <% if @profile.workAbroad == true %>
        <h4><i class="fa fa-plane"></i>&nbsp;&nbsp;<%= @profile.name %> is willing to work abroad</h4>
      <% else %>
        <h4><i class="fa fa-plane"></i>&nbsp;&nbsp;<%= @profile.name %> is not willing to work abroad</h4>
      <% end %><hr>
      <h4><i class="fa fa-gbp"></i>&nbsp;&nbsp;Expecting a salary of: £<%= @profile.salary %> </h4><hr>
      <h4>Prefer to work in these locations:</h4>
      <div class="eachcity">
        <% @profile.cities.each do |city| %>
          <li>
            <h4><i class="fa fa-check"></i>&nbsp;<span><%= city.name %></span></h4>
          </li>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="portfolioContainer">
  <h1><b>My Portfolio</b></h1>
  <hr>
  <div class="eachportfolio">
    <% @profile.portfolios.each do |portfolio| %>
      <article class="caption">
        <%= image_tag portfolio.picture.url,:size => "300x300", class: "caption__media img" %>
          <div class="caption__overlay">
            <p class="caption__overlay__content">
              <%= portfolio.description %>
            </p>
          </div>
      </article>
    <% end %>
  </div>
</div>

<div class="workContainer">
  <h1><b>Work Experience</b></h1>
  <h4><%= @profile.name %> has <%= @profile.experiance %> experience</h4>
  <div class="eachworks">
    <% @profile.works.each do |work| %>
      <h3><i class="fa fa-briefcase">&nbsp;&nbsp;</i><b><%= work.companyName %></b>
        <span class="date">&nbsp;&nbsp;<%= work.startDate.month %>/<%= work.startDate.year %> - <%= work.finishDate.month %>/<%= work.finishDate.year %></span></h3>
      <h4><b><%= work.position %></b></h4>
      <p><%= work.workDescription %></p>
      <hr>
    <% end %>
  </div>
</div>

<% unless @profile.user.github_profile.nil? %>
  <div class="githubContainer">
    <h1><span class="icon"><i class="fa fa-github fa-1x"></i></span>&nbsp;<b>Github Profile</b></h1>
    <div class="publicrepos">
      <% @repositories.each do |repo| %>
        <%= link_to repo[:html_url] do %>
          <div class="repo">
            <b><h4><%= h truncate(repo[:name].upcase, :length => 20) %></h4></b>
            <h4>contributions: <%= repo[:contributions] %></h4>
            <h5><i class="fa fa-code-fork"></i> <%= repo[:forks]%>&nbsp;&nbsp;&nbsp;<i class="fa fa-eye"></i> <%= repo[:watchers] %> <span style="float:right; color:#AEA8D3;"><%= repo[:language] %> </span> </h5>
            <hr>
            <p><%= h truncate(repo[:description], :length => 200) %><span style="float:right; color:#AEA8D3;">View source code</span></p>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
<% end %>

<div class="contactContainer">
  <% if recruiter_signed_in? %>
    <% if !@joined %>
      <h4>You can contact your relevant candidates for just £1 per contact.<br> There are no subscriptions or up-front fees.</h4>
      <%= form_tag pay_path, id:"chargeForm" do %>
        <script src="https://checkout.stripe.com/checkout.js"></script>
        <%= hidden_field_tag 'stripeToken' %>
        <%= hidden_field_tag 'stripeEmail' %>
        <%= hidden_field_tag 'profile_id', @profile.id %>
        <button id="customButton" class="btn btn-primary btn-lg btn-border custom">Purchase £1</button>
        <script>
        var handler = StripeCheckout.configure({
          key: 'MYTESTKEYHERE',
          image: '/img/documentation/checkout/marketplace.png',
          locale: 'auto',
          token: function(token, arg) {
            $('#stripeToken').val(token.id);
            $('#stripeEmail').val(token.email);
            $('#chargeForm').submit();
          }
        });
        $('#customButton').on('click', function(e) {
          // Open Checkout with further options
          handler.open({
            name: 'Ulearnr',
            description: '2 widgets',
            currency: "gbp",
            amount: '<%= @amount %>'
          });
          e.preventDefault();
        });
        </script>
      <% end %>
    <% else %>
      <button type="button" class="btn btn-primary btn-lg btn-border custom" data-toggle="modal" data-target="#myModal">
      View Contacts
      </button>
      <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel"><%= @profile.name %> Contacts</h4>
          </div>
          <div class="modal-body">
            <p>
              Get in touch with <%= @profile.name %> using the following methods:
            </p><br>
            <div class="">
              <p>
                Email: <span class="dets"><b><%= @profile.user.email %></b><br></span>
                Contact number: <b><%= @profile.phone %></b>
              </p>
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
      </div>
    <% end %>
  <% end %>
  <br>
  <% if recruiter_signed_in? %>
    <%- unless current_recruiter.favorite_profiles.exists?(id: @profile.id) -%>
      <%= link_to 'Add to favorites', favorite_profiles_path(profile_id: @profile), method: :post %>
    <%- else -%>
      <%= link_to 'Remove from favorites', favorite_profile_path(@profile), method: :delete %>
    <%- end -%>
  <% end %>

</div>




<script type="text/javascript">
$('.cd-trigger').on('click', function(event){

$('.cd-quick-view').css({
    "top": topSelected, // this is the selected image top value
    "left": leftSelected, // this is the selected image left value
    "width": widthSelected, // this is the selected image width
}).velocity({
  //animate the quick view: animate its width and center it in the viewport
  //during this animation, only the slider image is visible
    'width': sliderFinalWidth+'px',
    'left': finalLeft+'px', // ($(window).width - sliderFinalWidth)/2,
    'top': finalTop+ 'px', // ($(window).height - slider final height)/2,
}, 1000, [ 400, 20 ])
.velocity({
  'width': quickViewWidth+'px', // 80% of the viewport
  'left': quickViewLeft+'px', // 10% of the viewport
}, 300, 'ease' ,function(){
  //show quick view content
  $('.cd-quick-view').addClass('add-content');
}).addClass('is-visible');

//assign .overlay-layer class to the body, assign the .empty-box class to the selected .cd-item
//...

});
</script>