config/routes.rb
Rails.application.routes.draw do
  devise_for :recruiters, controllers: {registrations: "recruiters/registrations"}
  resources :cities
  resources :expertises
  devise_for :users, controllers: {registrations: "users/registrations", omniauth_callbacks: "callbacks"}
  get 'recruiter/home'
  get 'recruiter/favoriteDevelopers'
  get 'recruiter/suggestedDevelopers'
  get 'developer/home'
  get 'home/index'
  get 'skills/:skill', to: 'profiles#index', as: "skill"
  post '/pay' => 'charge#pay'
  resources :profiles
  resources :favorite_profiles, only: [:create, :destroy]

  root 'home#index'

end

app/views/partials/_footer.html.erb
<h5>FOLLOW US</h5> <br>
<div class="socialbuttons">
  <i class="fa fa-facebook fa-2x"></i>&nbsp;&nbsp;
  <i class="fa fa-twitter fa-2x"></i>&nbsp;&nbsp;
  <i class="fa fa-youtube-play fa-2x"></i>&nbsp;&nbsp;
  <i class="fa fa-instagram fa-2x"></i>
</div>

app/views/partials/_recruiter_nav_bar.html.erb
<ul class="nav navbar-nav navbar-right">
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">My Account <span class="caret"></span></a>
      <ul class="dropdown-menu">
        <li><%= link_to "View all Developers", profiles_path %></li>
        <li role="separator" class="divider"></li>
        <li><%= link_to "Saved Developers", recruiter_favoriteDevelopers_path %></li>
        <li role="separator" class="divider"></li>
        <li><%= link_to "Account Details", edit_recruiter_registration_path %></li>
        <li role="separator" class="divider"></li>
        <li><%= link_to "Logout", destroy_recruiter_session_path, method: :delete %></li>
      </ul>
    </li>
</ul>

app/views/partials/_user_nav_bar.html.erb
<ul class="nav navbar-nav navbar-right">
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">My Account <span class="caret"></span></a>
      <ul class="dropdown-menu">
        <li><%= link_to "Edit Profile", edit_profile_path(current_user) %></li>
        <li><%= link_to "View Profile", profile_path(current_user) %></li>
        <li role="separator" class="divider"></li>
        <li><%= link_to "Account Setting", edit_user_registration_path %></li>
        <li role="separator" class="divider"></li>
        <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
      </ul>
    </li>
</ul>