config/routes.rb
Rails.application.routes.draw do
  devise_for :recruiters, controllers: {registrations: "recruiters/registrations"}
  resources :cities
  resources :expertises
  devise_for :users, controllers: {registrations: "users/registrations", omniauth_callbacks: "callbacks"}
  get 'recruiter/home'
  get 'recruiter/favoriteDevelopers'
  get 'recruiter/suggestedDevelopers'
  get 'developer/home'
  get 'home/index'
  get 'skills/:skill', to: 'profiles#index', as: "skill"
  post '/pay' => 'charge#pay'
  resources :profiles
  resources :favorite_profiles, only: [:create, :destroy]

  root 'home#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CodeProject</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link href='https://fonts.googleapis.com/css?family=Comfortaa:400,700' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <style media="screen">
  .container-full {

      width: 100%;
    }

  .contentcontainer{
    width: 100%;
  }

  .custom{
    background-color: white;
    border-color: white;
    border-radius: 0;
  }
  .logo{
    font-family: 'Comfortaa', cursive;
    padding-left: 30px;
    font-size: 20px;
  }
  .links{
    font-family: 'Comfortaa', cursive;
    color: #674172;
  }
  </style>

</head>
<body>

  <div class="container-full">

  <nav class="navbar navbar-default custom">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "M  Y    D  E  V", root_path, :class => "navbar-brand logo" %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right links">
          <% if !person_signed_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Sign in <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Developer Sign in", new_user_session_path %></li>
                <li><%= link_to "Recruiter Sign in", new_recruiter_session_path %></li>
              </ul>
            </li>
          <% end %>
          <li><%= link_to "Developers", developer_home_path %></li>
          <li><%= link_to "Recruiters", recruiter_home_path %></li>
          <li><%= link_to "Create Expertise", new_expertise_path %></li>
          <li><%= link_to "Create City", new_city_path %></li>
        </ul>
        <% if user_signed_in? %>
          <%= render 'partials/user_nav_bar' %>
        <% elsif recruiter_signed_in? %>
         <%= render 'partials/recruiter_nav_bar' %>
        <% end %>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

  <div class="contentcontainer">
      <%= yield %>
  </div>

</div>

</body>
</html>